### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mh-cbon**
Hi,

Spent quiet a few time to fail to announce non standard service.
Hope this may help someone else !

### CODE REVIEW

**Comment by watson** [comment]
@mh-cbon did you try to announce an official service listen on the IANA list, but with a wrong port? Or did you want to make your own custom service name not listed on the IANA list?

**Comment by mh-cbon** [comment]
Hi,

I tried to announce ~~non sense~~ custom service __type__ on my router.
But it won t accept it at all (not a professional/open material).

Does the port number matters too ? I have not noticed that. I was playing around the service type only.

**Comment by watson** [comment]
@mh-cbon I'm not sure what you mean by that you tried to advertise it on your router. Did you install this module on your router?

You network doesn't care about the name or the port number. Your router should happily broadcast whatever your send to it to everyone on the network. It's up to the clients whether or not they will accept it.

Say you create a new type of video server called - you call it "Foobar Videos" and you want to advertise it on the network under the name `foobar`. You just advertise the service name `foobar` with the port that it's listening on. As long as you also have a client that listens for that then you are ok. Of cause if your client have no idea what the `foobar` service type is, then it won't work. If your client is an AirPlay client, it will not understand `foobar`, only `airplay` and `raop` which is the two services the the AirPlay protocol expects. Does that make sense?

**Comment by watson** [comment]
@mh-cbon in regards to weather or not the port is important, that will be up to the client. If the client is really picky about the port then it matters, but plenty of service types doesn't care. E.g. all the `ipp` clients I've worked with doesn't care about the port. They will just connect to whatever port you advertise

**Comment by watson** [comment]
@mh-cbon btw, don't get me wrong here. I think it's good to mention the link you added to the readme :smiley: - it's a good resource for people to know about. I just don't think it should be required that they use one from the list... it should be optional I think. That's why I'm trying to figure out what problem you experienced :smiley:

**Comment by mh-cbon** [comment]
Hi !

Yeah agreed, a simple mention is better.

See how i proceeded,
Terminal 1
```
$ bonjour
LIVEBOX [xx:xx:xx:xx:xx:xx]._workstation._tcp.local
LIVEBOX._http._tcp.local
```

Terminal 2
```
$ bonjour-publish -P 5060 -T some
Announce 'nop, no title set' on :5060 as some
Options {}
```

Terminal 1 won t show the new service. I guess it s because my router is picky about the service type.

Now if i announce an `http` service type, it works fine !
```
$ bonjour-publish -P 5060 -T http
Announce 'nop, no title set' on :5060 as http
Options {}
```

```
$ bonjour
LIVEBOX [xx:ss:ss:xx:xx:xx]._workstation._tcp.local
LIVEBOX._http._tcp.local
nop, no title set._http._tcp.local
```

That works fine for `http` and `rfb` (vnc stuff), but i can t announce stuff like `ftp` or `smtp` or `non-sense`.

Seems my router won t allow that.

In the end, it just mean i will rely on service __name__ field to id my service type ;)

**Comment by mh-cbon** [comment]
I tried an update, but my english is non standard too, you may want to refactor for clarity and correctness : )

**Comment by watson** [comment]
Thanks for explaining :smiley: To me it seems extremely weird that your router should even care the slightest about this. Your router just passes on this sort of DNS packets. It doesn't validate it - it would have no idea how. Also, according to the RFC, it's perfectly ok to make up your own names, so your router would be in violation of the RFC if it did block. I think something else is going on here - maybe a bug in either `bonjour-browser` or `bonjour`.

**Comment by watson** [comment]
@mh-cbon merged :smiley: Thanks for contributing to the project!

**Comment by mh-cbon** [comment]
> I think something else is going on here - maybe a bug in either bonjour-browser or bonjour.

I really believe the router does block it, found this tool on my box here which gives same results as your impl. of bonjour,

```
avahi-browse --all
+ wlp2s0 IPv4 kenshiro's remote desktop on pc14.home        VNC Remote Access    local
+ wlp2s0 IPv4 nop, no title set                             VNC Remote Access    local
+ wlp2s0 IPv4 nop, no title set                             Web Site             local
+ wlp2s0 IPv4 LIVEBOX                                       Web Site             local
+ wlp2s0 IPv4 LIVEBOX [xx:xx:xx:xx:xx:xx]                   Workstation          local
```


> Thanks for contributing to the project!
Thanks for publishing it initially ! That s least i can do :)

**Comment by watson** [comment]
Thnx, I'll see if I can reproduce it

**Pull request merged**
