### PR TITLE
Replace simple dependency and drop 12 sub-deps 🎉  

### PR DESCRIPTION
**Pull request by fregante**
Faster and lighter? Sign me up!

https://www.npmjs.com/package/fast-deep-equal

`deep-equal` is downloading a lot of dependencies: https://npm.broofa.com/?q=bonjour

### CODE REVIEW

**Comment by fregante** [comment]
I know this repo is dormant, but the 2 packages are equivalent and would be a pretty easy improvement.

**Comment by mdidon** [comment]
@fregante We have implemented in https://github.com/onlxltd/bonjour-service if this is of any use.

**Comment by jhurliman** [comment]
@mdidon great to see active development on a successor project? Does it address https://github.com/watson/bonjour/issues/51 by chance?

**Comment by mdidon** [comment]
@jhurliman Thanks for bringing this to my attention.
Not yet, we're working through the issues/PRs listed under the original repo but I'll have a look into it next week.

**Comment by fregante** [comment]
Friendly ping @watson. 😃  I know this repo is dormant, but the 2 packages are equivalent and would be a pretty easy improvement.

**Comment by toastal** [comment]
In April 2022, v12 was EoL as well. Might as well move the goal post to v14 for latest maintained LTS. It would be nice to get a smaller bundle and better performance.

**Pull request closed without merging**
