### PR TITLE
Add rinfo from the udp response to the service object

### PR DESCRIPTION
**Pull request by jlucidar**
I don't know if it is relevant to anyone else than me but I need to access this information for one of my program. (I need to know with which address the server replied).

It does not break anything and passed the tests, though...

Anyway if you want to merge it, it's ready. if you don't, I will continue to use my fork for my project.

### CODE REVIEW

**Comment by watson** [comment]
@jlucidar just to make sure I understand your use-case: You send an mdns query and when you get the response you want to know the IP address of the interface that the remote server responded using?

**Comment by jlucidar** [comment]
correct, I want to know with which address the remote server used to reply.

**Comment by watson** [comment]
@jlucidar hmm it sounds like a very fringe use-case. What do you need it for?

**Comment by jlucidar** [comment]
backward compatibility with a handmade discovery protocol. and being able to apply my own logic to choose the interface I want to talk to (ethernet vs wifi vs usb over ethernet, etc ...) in case of the server being connected to different networks. It is specific, but also a good way to automate discovery and connect over complex network topology.

**Comment by watson** [comment]
@jlucidar So if a service is a member of to both en0 and en1 and have two difference IP's, you want to know the interface that was used to respond to the mdns query? (in case that the dns server is actually the same as the service)

**Comment by jlucidar** [comment]
correct.

**Comment by watson** [comment]
@jlucidar You are aware that it's not given that the responding server is the same as the service it's responding for?

I'm thinking we should call this something more specific that simply `rinfo` - maybe `mdnsRinfo` or something, just to make sure users know that this is the rinfo of the mdns responder - not the service (though those are the same in many cases)

**Comment by jlucidar** [comment]
@watson : yes I do. but it doesn't matter in my case.

ok for the changes, I'm making it right now.

**Comment by watson** [comment]
@jlucidar I'm sorry for the back and forth here... just needed to wrap my head around this. After thinking it over and talking to others, I think a better word would be `referer`. I'll just rename it my self and merge the PR 😃 - Thanks for answering all my silly questions

**Comment by watson** [comment]
@jlucidar It's on npm as v3.5.0 😃

**Comment by jlucidar** [comment]
nice ! thank you :)

**Pull request merged**
